create schema bakery;

-- auto-generated definition
create sequence if not exists general_id_sequence
    maxvalue 10000000;

comment on sequence general_id_sequence is 'General sequence for all the IDs generated by the application';

alter sequence general_id_sequence owner to postgres;
