create database bakerydb;
create schema bakery;

create sequence bakery.general_id_sequence
	maxvalue 10000000;
comment on sequence bakery.general_id_sequence is 'General sequence for all the IDs generated by the application';

create table bakery.category
(
	id int default nextval('bakery.general_id_sequence')
		constraint category_pk
			primary key,
	name varchar(250) not null,
	is_active bool default false
);

create table bakery.item
(
	id int default nextval('bakery.general_id_sequence')
		constraint item_pk
			primary key,
	name varchar(50) not null,
	description varchar(200) not null,
	price decimal(10,2) not null
);

comment on table bakery.item is 'item table, which contains information about the items being soid';


create table bakery.catalog_information
(
	id int not null,
	quantity_available int not null,
	unit_of_measurement varchar(25) not null,
	sku varchar(25),
	is_active bool default false
);

create unique index catalog_information_id_uindex
	on bakery.catalog_information (id);

alter table bakery.catalog_information
	add constraint catalog_information_pk
		primary key (id);
